apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result:before
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: result-app
  namespace: vote
spec:
  type: NodePort
  selector:
    app: result
  ports:
  - protocol: TCP
    port : 5001
    targetPort: 80
    nodePort: 31001