apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote:before
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: voting-app
  namespace: vote
spec:
  type: NodePort
  selector:
    app: vote
  ports:
  - protocol: TCP
    port : 5000
    targetPort: 80
    nodePort: 31000